// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xiycyausucodmfjdfoge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhpeWN5YXVzdWNvZG1mamRmb2dlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMTY2MTQsImV4cCI6MjA2OTY5MjYxNH0.hhiPC-CJpKjrtFYTMjh0ktiQ_1kIgwxi4UPtUvxzHsg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});